---
- name: set files path
  set_fact:
    files_path: "{{ role_path }}/files"
  tags:
    - always

- name: configure zsh
  import_tasks: zsh.yml
  tags:
    - zsh

- name: osx defaults
  import_tasks: osx.yml
  tags:
    - osx
